[package]
name = "monitor"
version = "0.1.0"
authors = ["The Kata Containers community <kata-dev@lists.katacontainers.io>"]
edition = "2018"
license = "Apache-2.0"

[[bin]]
name = "kata-monitor"
path = "src/bin/main.rs"

[dependencies]
anyhow = "^1.0"
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
url = "2.3.1"
go-flag = "0.1.0"
futures-util = { version = "0.3", default-features = false }
logging = { path = "../../../libs/logging"}
slog = "2.5.2"
slog-scope = "4.4.0"
runtimes = { path = "../runtimes" }
prometheus = { version = "0.13.0", features = ["process"] }
procfs = "0.12.0"
lazy_static = "1.2"
